/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ideabaker.samples.gradle

import com.ideabaker.sample.gradle.multi.service.MessageService

class App

fun main() {
  println(MessageService.generateMessage())
}
